# Generated by Django 4.2.5 on 2023-09-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_item_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='borrowed_items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
